Adding minimal npm build
keycloak/keycloak-gh-actionbot pull request #10
Opened 2022-09-26 13:03 UTC by ahus1

Closes #9

2022-09-26 13:05 UTC, ahus1 commented
@jonkoops - I'd be happy if you give it a review when you have the time. 

The PR actions didn't run here, yet, apparently as this adds the first workflow definition.

You can view successful run of the action in my forked repository: https://github.com/ahus1/keycloak-gh-actionbot/actions

2022-09-26 17:41 UTC, jonkoops requested changes

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +  pull_request:
Let's restrict this to PRs to the `main` branch and direct commits on the `main` branch.
```suggestion
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v3
Can we add a name for this step as well?
```suggestion
      - name: Check out repository
        uses: actions/checkout@v3
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +name: Build
This workflow does more than just build the project. Perhaps it can be better named?
```suggestion
name: CI
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +name: Build
Since this is the only workflow I think we can call it `main,yml`, which seems to be the convention in the Github docs.

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +          node-version: '16.x'
This can be simplified a bit.
```suggestion
          node-version: 16
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +          cache: 'npm'
No need for quotes here.
```suggestion
          cache: npm
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +          cache: 'npm'
We might want to pass [`check-latest`](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version) here, so that the latest version of Node.js in the version range is used always.
```suggestion
          check-latest: true
          cache: npm
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +      - name: Build
Let's put the installation of dependencies in a separate step. Also, let's use [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci) which guarantees lockfile correctness.
```suggestion
      - name: Install dependencies
        run: npm ci

      - name: Build
```

2022-09-26 17:41 UTC, jonkoops commented on .github/workflows/ci.yml
> +          npm run format
Running `format` will skip possible errors as it runs Prettier using `--write`. This should fail instead. Also, we should put this into a separate step.

2022-09-28 09:31 UTC, ahus1 commented on .github/workflows/ci.yml
> +  pull_request:
The setting for "push" would prevent the action to run on forks where people create their feature branches. Therefore I'd like to keep the setting for "push" as is.

I'll add the setting for pull_requests though.

2022-09-28 09:43 UTC, ahus1 commented
Hi @jonkoops - this is now ready for another review round. 

You can view successful run of the action in my forked repository: https://github.com/ahus1/keycloak-gh-actionbot/actions

I am not sure why those are not running on this repository; might be that this is the first action we add? If the don't run on main, I'll investigate with Stian later who has more access rights for the settings.

2022-10-04 21:21 UTC, ahus1 commented
All review comments except one accepted, assume "[lazy consensus](https://community.apache.org/committers/lazyConsensus.html)" on this one.

2022-10-04 21:21 UTC, merged

2022-10-04 21:23 UTC, jonkoops commented
This fell off my radar for a bit, but all looks good @ahus1!