Initial bot setup to support re-running failed workflows.
keycloak/keycloak-gh-actionbot pull request #2
Opened 2022-08-22 07:12 UTC by ahus1

First iteration to provide a GitHub Action based bot.

Closing #1

2022-08-22 09:33 UTC, jonkoops requested changes

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +#!/usr/bin/env node
I don't think we need a shebang here, the environment is aware of the context in which this file is executed.
```suggestion
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +const { Octokit, App } = require("octokit");
Once ESM mode is enabled this could be refactored to:
```suggestion
import core from "@actions/core";
import github from "@actions/github";
import { Octokit, App } from "octokit";
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +    const debug = core.getInput("debug") === "true" || false;
No need to use a fallback here, the value will always be a boolean.
```suggestion
    const debug = core.getInput("debug") === "true";
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +            )}`
You can always pass multiple values (including complex objects) to the console.
```suggestion
        console.log('Event payload:', github.context.payload);
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +const github = require("@actions/github");
As far as I can see we're only using the exported `context` member here, so why not import only that?
```suggestion
const { context } = require("@actions/github");
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +        const pull_number = github.context.payload.issue.number;
The `issue` field is used in some conditionals later on, so it might be good to destructure it for easier access.
```suggestion
        const { issue } = github.context.payload;
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +    console.error(`response failed ${JSON.stringify(response, undefined, 2)}`);
The console can format objects for you.
```suggestion
    console.error('response failed:', response);
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +            await octokit.request(
Instead of using `.request` I think you can use `.pulls.get` and get back the same data without needing to write out the endpoint.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                `Pull request: ${JSON.stringify(pull_request, undefined, 2)}`
The console can format objects for you.
```suggestion
                'Pull request:', pull_request
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +            await octokit.request(
There must also be method that is [already defined](https://octokit.github.io/rest.js/v18) inside Octokit, let's use that instead of the hardcoded endpoint.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +            const check = check_runs[i];
Let's use a regular `.forEach` here.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                        `Check: ${JSON.stringify(check, undefined, 2)}`
The console can log objects for us.
```suggestion
                        'Check:', check`
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                    await octokit.request(
Same here, let's use one of the methods instead of providing an endpoint.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                    console.log(`Job: ${JSON.stringify(job, undefined, 2)}`);
The console can format objects for us.
```suggestion
                    console.log('Job:', job);
```

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                        "POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs",
Same here, let's use one of the methods instead of providing an endpoint.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +                "POST /repos/{owner}/{repo}/issues/comments/{comment_id}/reactions",
Same here, let's use one of the methods instead of providing an endpoint.

2022-08-22 09:33 UTC, jonkoops commented on index.js
> +        for (let i = 0; i < check_runs.length; i++) {
This could be sped up by running the Promises in parallel with [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

2022-08-22 12:35 UTC, ahus1 commented on .gitignore
> +node_modules
I agree this can be reduced, still I'd like to keep `.idea` in there for convenience.

2022-08-22 12:36 UTC, ahus1 commented on MAINTAINERS.md
> +* [Alexander Schwartz](https://github.com/ahus1)
Thanks, happy to have you on board! Will be part of the next commit.

2022-08-22 12:38 UTC, ahus1 commented on MAINTAINERS.md
> +Maintainers
I'd like to keep this in line with the other Keycloak repositories, at least for this PR. I've only seen MAINTAINERS.md there.

2022-08-22 12:41 UTC, ahus1 commented on README.md
> +2. Run `yarn install` to install the dependencies.
ok, changed in next commit

2022-08-22 12:42 UTC, ahus1 commented on README.md
> +4. Run `yarn format` and `yarn dist` to package the changes to `dist/index.js`.
I'd like to keep that for a future commit, as I'm not a pre-commit hook practitioner myself. Let's first see if the GHA works as epected.

2022-08-22 12:47 UTC, ahus1 commented on README.md
> +* Push the changes to the release branch for those who track only the major version (like `v1`)
I'd like to keep that for the next iteration. If you'd like to keep track of it, could you please create an issue?

2022-08-22 12:49 UTC, ahus1 commented on package.json
> +  "dependencies": {
part of the next commit

2022-08-22 12:50 UTC, ahus1 commented on package.json
> +  "author": "",
part of next commit

2022-08-22 12:51 UTC, ahus1 commented on package.json
> +    "format": "prettier --write '*.js' --tab-width=4"
part of the next commit

2022-08-22 12:51 UTC, ahus1 commented on package.json
> +    "prettier-cli": "^0.1.0"
part of the next commit

2022-08-22 12:56 UTC, ahus1 commented on index.js
> +        const pull_number = github.context.payload.issue.number;
part of next commit

2022-08-22 13:00 UTC, ahus1 commented on index.js
> +            await octokit.request(
will be part of the next commit. The REST API docs seem to always use the setup with the URL. Anyway, changed in next commit.

2022-08-22 13:07 UTC, ahus1 commented on index.js
> +            await octokit.request(
part of next commit

2022-08-22 13:08 UTC, ahus1 commented on index.js
> +                    await octokit.request(
part of next commit

2022-08-22 13:09 UTC, ahus1 commented on index.js
> +                        "POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs",
part of next commit

2022-08-22 13:09 UTC, ahus1 commented on index.js
> +                "POST /repos/{owner}/{repo}/issues/comments/{comment_id}/reactions",
part of next commit

2022-08-22 14:42 UTC, ahus1 commented on README.md
> +## Releasing changes for the bot
ok, added `npm version`

2022-08-22 14:46 UTC, ahus1 commented on index.js
> +            const check = check_runs[i];
Changed it to `for (const check of check_runs) {` that hopefully less ugly. Yes, `forEach` and `Promise` would be more efficient; still I'd find it hard to reason about the correct error handling there. I'd like to keep it as is for now (assuming that it is re-running 1-2 unstable action runs). Feel free to open an issue for that.

2022-08-22 14:49 UTC, ahus1 commented
Hi @jonkoops - thank you for the thorough review. My JavaScript skills are rusty and used seldom, good to have you on this review to see what I missed.

The latest commit has all the changes in it that I marked as resolved; all unresolved ones received a comment from me. I'd hope you will find it "good enough" - it still needs to be figured out if this is good enough for the Keycloak repo, and if we end up with too many action runs and need to turn to a real hosted GitHub Bot instead that just listens on a REST endpoint. 

Looking forward for your next review!

2022-08-25 10:25 UTC, jonkoops approved these changes

2022-08-25 10:25 UTC, jonkoops commented on .github/dependabot.yml
> +      interval: "daily"
No need to escape these values, as no reserved characters are used. You might also want to disable automatic rebasing as this can lead to a lot of CI backlogging. Also, settting a larger PR limit is a good idea as Dependabot might otherwise hide updates.

```suggestion
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 999
    rebase-strategy: disabled
    schedule:
      interval: daily
```

2022-08-25 10:25 UTC, jonkoops commented on .gitignore
> +dist/package.json
Under what circumstances would the package file end up in the `dist` directory? Perhaps this line can be removed?

2022-08-25 10:25 UTC, jonkoops commented on .gitleaks.toml
> +[allowlist]
What does this file do? I see no tooling in this repo that currently integrates with this.

2022-08-25 10:25 UTC, jonkoops commented on action.yml
> +  main: "dist/index.js"
Same here, I don't believe we actually need most of these quotations.
```suggestion
name: Keycloak Bot
description: Bot reacting on comments
inputs:
  github_token:
    description: GITHUB_TOKEN or a repo scoped PAT.
    required: true
  debug:
    description: Log additional information the console
    required: false
    default: "false"
runs:
  using: node16
  main: dist/index.js
```

2022-08-25 10:26 UTC, jonkoops commented
Looking good to me @ahus1!

2022-08-25 10:33 UTC, ahus1 commented on .gitignore
> +dist/package.json
This file ends up in the `dist` folder after I added `"type": "module"` to the `package.json` in the root folder. And adding the type was necessary to use `import`.

2022-08-25 10:33 UTC, ahus1 commented on .github/dependabot.yml
> +      interval: "daily"
thanks, will add this as suggested.

2022-08-25 10:36 UTC, ahus1 commented on .gitleaks.toml
> +[allowlist]
There was an automated leak scanning enabled by our organization, and that detected some string fragments that looked like key material, but where actually some string constants to detect a header for key material, not the key material itself.

I got mailed on my account, so I fixed it after talking to the owners of the bot.

2022-08-25 10:51 UTC, merged