Filter out non-GitHub-Action based checks
keycloak/keycloak-gh-actionbot pull request #7
Opened 2022-09-13 08:38 UTC by ahus1

Closes #6

The error can be reproduced with the following minimal `event.json` file as long as the PR 14318 in the Keycloak main repository is unchanged.

````
{
  "action": "created",
  "comment": {
    "author_association": "OWNER",
    "body": "/rerun"
  },
  "issue": {
    "number": 14318,
    "author_association": "OWNER",
    "pull_request": {},
    "state": "open"
  },
  "repository": {
    "owner": {
      "login": "keycloak"
    },
    "name": "keycloak"
  }
}
```

This also shows that this is fixed: When running with my personal access token it continues further and then complains that I don't have permission to re-run the job (this is expected).

2022-09-13 08:40 UTC, ahus1 commented
@mabartos - I'd like to have this PR in before releasing a new version as this makes this action fail with the most recent changes to the checks in the main Keycloak repository.

Feel free to chip-in for a review on this.

2022-09-15 08:24 UTC, mabartos approved these changes
@ahus1 LGTM! Thanks!

2022-09-15 09:14 UTC, jonkoops requested changes

2022-09-15 09:14 UTC, jonkoops commented on index.js
> +    JSON.stringify(context.payload)
The console should be able to handle objects, so there is no need to serialize this.
```suggestion
    context.payload
```

2022-09-15 09:14 UTC, jonkoops commented on README.md
> +## Testing the GitHub action locally
A pretty common way to do this in Node applications is to use `.env` files. Not quite sure if it would work here but check out https://www.npmjs.com/package/dotenv.

2022-09-15 09:16 UTC, ahus1 commented on index.js
> +    JSON.stringify(context.payload)
I'd like to have the event in JSON format on the console, as only then it can be used for debugging purposed and put in to an `event.json` file. That's why I used `JSON.stringify`.

2022-09-15 09:23 UTC, ahus1 commented on README.md
> +## Testing the GitHub action locally
@jonkoops - I used it in other projects, yes that would be nice. 

After your comment I'd tested if this works with GitHub action packages, and it turns out it doesn't. Therefore I'd keep it as is for now.

2022-09-15 09:29 UTC, jonkoops commented on README.md
> +## Testing the GitHub action locally
Sounds good to me 👍

2022-09-15 09:31 UTC, jonkoops commented on index.js
> +    JSON.stringify(context.payload)
But the console will format the JSON by default no?

2022-09-15 09:40 UTC, ahus1 commented on index.js
> +    JSON.stringify(context.payload)
@jonkoops - when printing on the console, it will print curly braces, but will use the wrong quotes (single quotes instead of double quotes), and will not put quotes around the keys that JSON would require. So the default will print `action: 'created'` when JSON requires `"action": "created"`.
So that's why I added an explicit call to JSON.

2022-09-15 13:13 UTC, jonkoops commented on index.js
> +    JSON.stringify(context.payload)
Seems valid for logging, but if we could still pretty-print this with:
```suggestion
    JSON.stringify(context.payload, null, 2)
```

WDYT?

2022-09-15 13:44 UTC, jonkoops approved these changes

2022-09-15 13:44 UTC, merged